#!/usr/bin/perl
#
use Astro::Api qw(:all);
use strict;
my $lat = "40";
my $lon = "74";
my $height = "0";
my $days = "2";
my $date = "2019-03-28";
my $offset = "-05:00";

my @lines = &Astro::Api::small($lat,$lon,$height,$days,$date,$offset);

# Print HTTP headers

print "Content-Type: text/xml;\n";
print "\n";

foreach my $line (@lines) {
    print "$line\n";
}
