#! gmake
#
# NOTE: make sure you are using GNU's "make-3.75.tar.gz" or older...
#
#
# A list of the files or directories that should NOT be 'made'
 STATIC = Makefile~ MakeInclude README README~ CVS gtopo30 astro_old astro_org testeph tran.tar

#
#.IGNORE:
#
include MakeInclude
#
