# based on: https://depot.dev/docs/integrations/github-actions#build-multi-platform-images-natively-without-emulation

name: depot-build

on:
  # you need to set workflow_dispatch to be able to run it manually:
  # https://stackoverflow.com/a/67523883/4070848
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Depot CLI
        uses: depot/setup-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # these secrets are set at repository level:
          # https://github.com/drmrbrewer/astro-api/settings/secrets/actions
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: depot/build-push-action@v1
        with:
          # these secrets are set at repository level:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          # what tags to apply to the generated image:
          # the images will be pushed to: https://hub.docker.com/repository/docker/drmrbrewer/astro-api/general
          tags: drmrbrewer/astro-api,drmrbrewer/astro-api:v20
          # where in the repo to run the build from:
          context: .
          # this is a multi-platform build... specify required platforms here:
          platforms: linux/amd64,linux/arm64
          # which (of several) Dockerfiles to use for the build:
          file: "Dockerfile-captain"
          # push to the Docker Hub (login credentials set above):
          push: true
          # following is to avoid an 'unknown/unknown' entry for 'OS/arch' showing (in addition to the ones you ask for) in the registry UI (probably just cosmetic, but annoying):
          # https://github.com/orgs/community/discussions/45969
          # https://docs.docker.com/build/attestations/#creating-attestations
          provenance: false
